<?php
/**
 * Helper functions used exclusively by the installation wizard.
 */

declare(strict_types=1);

/**
 * Run every server/environment requirement check.
 * Returns a list of ['label' => ..., 'ok' => bool, 'required' => bool, 'detail' => ...]
 */
function installer_check_requirements(): array
{
    $checks = [];

    $checks[] = [
        'label' => 'PHP version >= 8.2',
        'ok' => version_compare(PHP_VERSION, '8.2.0', '>='),
        'required' => true,
        'detail' => 'Detected PHP ' . PHP_VERSION,
    ];

    $extensions = ['pdo', 'pdo_mysql', 'mbstring', 'openssl', 'curl', 'fileinfo', 'json', 'session'];
    foreach ($extensions as $ext) {
        $checks[] = [
            'label' => "PHP extension: {$ext}",
            'ok' => extension_loaded($ext),
            'required' => true,
            'detail' => extension_loaded($ext) ? 'Loaded' : 'Missing',
        ];
    }

    $checks[] = [
        'label' => 'PHP extension: gd',
        'ok' => extension_loaded('gd'),
        'required' => false,
        'detail' => extension_loaded('gd') ? 'Loaded' : 'Missing (used for image processing, optional)',
    ];

    $writablePaths = [
        'config.php' => BASE_PATH . '/config.php',
        '/uploads' => BASE_PATH . '/uploads',
        '/logs' => BASE_PATH . '/logs',
        '/install' => BASE_PATH . '/install',
    ];

    foreach ($writablePaths as $label => $path) {
        $ok = is_file($path) ? is_writable($path) : (is_dir(dirname($path)) && is_writable(dirname($path)));
        if (is_dir($path)) {
            $ok = is_writable($path);
        }
        $checks[] = [
            'label' => "Writable: {$label}",
            'ok' => $ok,
            'required' => true,
            'detail' => $ok ? 'Writable' : 'Not writable — run: chmod 755 ' . $label,
        ];
    }

    return $checks;
}

function installer_requirements_passed(array $checks): bool
{
    foreach ($checks as $check) {
        if ($check['required'] && !$check['ok']) {
            return false;
        }
    }

    return true;
}

/**
 * Attempt a DB connection with the given credentials. Returns [success, message, pdo|null].
 */
function installer_test_db_connection(string $host, string $port, string $name, string $user, string $pass): array
{
    try {
        $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);

        return ['success' => true, 'message' => 'Connected successfully.', 'pdo' => $pdo];
    } catch (PDOException $e) {
        return ['success' => false, 'message' => 'Connection failed: ' . $e->getMessage(), 'pdo' => null];
    }
}

/**
 * Import database.sql using a connection with multi-statement support.
 */
function installer_import_schema(string $host, string $port, string $name, string $user, string $pass): array
{
    try {
        $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::MYSQL_ATTR_MULTI_STATEMENTS => true,
        ]);

        $sql = file_get_contents(BASE_PATH . '/database.sql');
        if ($sql === false) {
            return ['success' => false, 'message' => 'Could not read database.sql'];
        }

        $pdo->exec($sql);

        return ['success' => true, 'message' => 'Database schema imported successfully.'];
    } catch (Throwable $e) {
        return ['success' => false, 'message' => 'Schema import failed: ' . $e->getMessage()];
    }
}

/**
 * Write the final root config.php with real database credentials.
 */
function installer_write_config(array $db, string $appUrl): bool
{
    $appKey = bin2hex(random_bytes(32));

    $contents = "<?php\n"
        . "/**\n"
        . " * 9JACASH - Generated application configuration.\n"
        . " * Generated by the installation wizard on " . date('Y-m-d H:i:s') . "\n"
        . " */\n\n"
        . "declare(strict_types=1);\n\n"
        . "define('DB_HOST', " . var_export($db['host'], true) . ");\n"
        . "define('DB_PORT', " . var_export($db['port'], true) . ");\n"
        . "define('DB_NAME', " . var_export($db['name'], true) . ");\n"
        . "define('DB_USER', " . var_export($db['user'], true) . ");\n"
        . "define('DB_PASS', " . var_export($db['pass'], true) . ");\n"
        . "define('DB_CHARSET', 'utf8mb4');\n\n"
        . "define('APP_URL', " . var_export(rtrim($appUrl, '/'), true) . ");\n"
        . "define('APP_ENV', 'production');\n"
        . "define('APP_DEBUG', false);\n"
        . "define('APP_KEY', " . var_export($appKey, true) . ");\n"
        . "define('APP_INSTALLED_AT', " . var_export(date('Y-m-d H:i:s'), true) . ");\n";

    return (bool) file_put_contents(BASE_PATH . '/config.php', $contents, LOCK_EX);
}

function installer_write_lock(): bool
{
    return (bool) file_put_contents(
        BASE_PATH . '/install/installed.lock',
        'Installed at ' . date('Y-m-d H:i:s') . "\nDo not delete this file unless you intend to reinstall the platform.\n",
        LOCK_EX
    );
}

function installer_render_head(string $title, string $assetBase): void
{
    ?>
<!DOCTYPE html>
<html lang="en">
<head>
<script>(function(){var t=localStorage.getItem('9jacash_theme');if(t)document.documentElement.setAttribute('data-theme',t);})();</script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= e($title) ?> · 9JACASH</title>
<link rel="icon" href="<?= e($assetBase) ?>/images/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="<?= e($assetBase) ?>/css/vendor/bootstrap.min.css">
<link rel="stylesheet" href="<?= e($assetBase) ?>/css/vendor/bootstrap-icons.min.css">
<link rel="stylesheet" href="<?= e($assetBase) ?>/css/fonts.css">
<link rel="stylesheet" href="<?= e($assetBase) ?>/css/theme.css">
<style>
body{background:linear-gradient(160deg,var(--brand-navy) 0%,var(--brand-navy-dark) 60%);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:32px 16px;}
.install-card{width:100%;max-width:640px;background:var(--surface);border-radius:var(--radius);box-shadow:var(--shadow);padding:36px;}
.brand-mark-sm{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--brand-gold),var(--brand-gold-dark));display:inline-flex;align-items:center;justify-content:center;color:var(--brand-navy);font-weight:800;}
.step-nav{display:flex;justify-content:space-between;gap:8px;}
.step-dot{flex:1;text-align:center;padding:10px 4px;border-radius:10px;background:var(--surface-alt);border:1px solid var(--border);}
.step-dot span{display:block;width:26px;height:26px;line-height:26px;border-radius:50%;background:var(--border);margin:0 auto 4px;font-weight:700;font-size:.8rem;}
.step-dot small{display:block;font-size:.7rem;color:var(--text-muted);}
.step-dot.active{border-color:var(--brand-emerald);}
.step-dot.active span{background:var(--brand-emerald);color:#fff;}
.step-dot.done span{background:var(--success);color:#fff;}
</style>
</head>
<body>
    <?php
}

function installer_render_foot(string $assetBase): void
{
    ?>
<script src="<?= e($assetBase) ?>/js/vendor/bootstrap.bundle.min.js"></script>
<script src="<?= e($assetBase) ?>/js/theme.js"></script>
<script src="<?= e($assetBase) ?>/js/main.js"></script>
</body>
</html>
    <?php
}
